int num1 = new Random().Next(1,100);
int num2 = new Random().Next(1,100);
int num3 = new Random().Next(1,100);
int num4 = new Random().Next(1,100);
int num5 = new Random().Next(1,100);
int num6 = new Random().Next(1,100);
Console.Write(num1);
Console.Write(" ");
Console.Write(num2);
Console.Write(" ");
Console.Write(num3);
Console.Write(" ");
Console.Write(num4);
Console.Write(" ");
Console.Write(num5);
Console.Write(" ");
Console.WriteLine(num6);
int max = num1;
if (num1 > max) max = num1;
if (num2 > max) max = num2;
if (num3 > max) max = num3;
if (num4 > max) max = num4;
if (num5 > max) max = num5;
if (num6 > max) max = num6;
Console.Write("Maximum number is ");
Console.WriteLine(max);